test the built image against postgresql
tigattack/Patchman-Docker pull request #62
Opened 2024-08-08 20:52 UTC by klaernie

this is a verbatim copy of the mariadb test against, testing against a
16.3 postgresql image based on alpine (16.4 is still building in the
docker library).

2024-08-08 20:53 UTC, klaernie commented
FYI: I took the liberty of renaming the mariadb test directory for clarity when my brain visits these directories late in the night some day..

2024-08-09 16:26 UTC, klaernie commented
another addendum: the last commit splits building the image and pushing it to the registry into two separate parts, so the pushing half can be skipped in a pull request triggered run - with the result that the build and test phases could complete and test the code without needing access to ghcr.io/tigattack

2024-08-16 10:58 UTC, tigattack requested changes
Hey, this is great, thank you!

I've suggested a couple of fixes for the old mariadb test path.

Thanks for working on the fix for PR runs too, I'd been meaning to take a look at that. Without having checked yet, I'm wondering if the "Build and push image" step, now moved to the end of the `build` job, couple be optimised at all. Maybe the already built image could be loaded and pushed without building it again before pushing? I imagine it'll use the cache from the first push (though I've never tested using a cache created earlier on in the same job myself), but it still feels slightly inefficient to build twice.

2024-08-16 10:58 UTC, tigattack commented on .github/workflows/build.yml
>          compose-file: .github/test/docker-compose.yml
```suggestion
        compose-file: .github/test-mariadb/docker-compose.yml
```

2024-08-16 10:58 UTC, tigattack commented on .github/workflows/build.yml
>          PWD: ${{ github.workspace }}/.github/test
```suggestion
        PWD: ${{ github.workspace }}/.github/test-mariadb
```

2024-08-16 13:17 UTC, klaernie commented
Oh, now the test revealed another flaw - the postgres and mariadb servers need to use different ports. I'll fix that once I have access to something better than my phone..

2024-08-16 13:36 UTC, klaernie commented
Now it finally runs properly.. but that docker compose action bug needs a deeper look from me later on..

2024-08-19 09:23 UTC, tigattack approved these changes
Cheers, looks good!

2024-08-19 09:24 UTC, merged